apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "cls-backend-application.fullname" . }}-database-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cls-backend-application.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: local-secret-manager
    kind: ClusterSecretStore
  target:
    name: cls-backend-db-password
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        DATABASE_URL: |
          postgres://{{ .Values.database.username }}:{{ "{{ .password }}" }}@{{ .Values.database.instanceName }}:5432/{{ .Values.database.databaseName }}?sslmode=require
  data:
  - secretKey: password
    remoteRef:
      key: cls-backend-db-password
      version: latest
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}