{{- if not .Values.gcp.project }}
{{- fail "gcp.project is required" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cls-backend-application.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cls-backend-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Google Cloud Project ID
  GOOGLE_CLOUD_PROJECT: {{ .Values.gcp.project | quote }}

  # Database connection URL template (password will be injected at runtime)
  # Uses auto-discovered Cloud SQL instance from helm-cloud-resources chart
  DATABASE_URL_TEMPLATE: "postgres://{{ include "cls-backend-application.getDatabaseUsername" . }}:__PASSWORD__@{{ include "cls-backend-application.getDatabaseInstanceName" . }}:5432/{{ include "cls-backend-application.getDatabaseName" . }}?sslmode=require"