{{- if not .Values.gcp.project }}
{{- fail "gcp.project is required" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cls-backend-application.fullname" . }}-secrets
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "cls-backend-application.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Google Cloud Project ID
  GOOGLE_CLOUD_PROJECT: {{ .Values.gcp.project | quote }}

