{{- if .Values.gcp.project }}
{{- include "cls-backend-cloud-resources.validateCrossChartParams" . }}
---
# Cloud SQL PostgreSQL Instance
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ .Values.database.instance.name }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "cls-backend-cloud-resources.labels" . | nindent 4 }}
spec:
  databaseVersion: {{ .Values.database.instance.version }}
  region: {{ .Values.gcp.region }}
  settings:
    tier: {{ .Values.database.instance.tier }}
    diskSize: {{ .Values.database.instance.diskSize }}
    diskType: {{ .Values.database.instance.diskType }}
    diskAutoresize: true
    diskAutoresizeLimit: 100
    ipConfiguration:
      ipv4Enabled: true
      authorizedNetworks: []
      requireSsl: false
    backupConfiguration:
      enabled: true
      pointInTimeRecoveryEnabled: true
      retainedBackups: 7
    maintenanceWindow:
      day: 7  # Sunday
      hour: 2 # 2 AM
      updateTrack: "stable"
    deletionProtection: false  # Set to true for production

---
# Database within the instance
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: {{ .Values.database.database.name | replace "_" "-" }}
  namespace: config-connector
  labels:
    {{- include "cls-backend-cloud-resources.labels" . | nindent 4 }}
spec:
  resourceID: {{ .Values.database.database.name | quote }}
  charset: "UTF8"
  collation: "en_US.UTF8"
  instanceRef:
    name: {{ .Values.database.instance.name }}

---
# Database user
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: {{ .Values.database.user.name | replace "_" "-" }}
  namespace: config-connector
  labels:
    {{- include "cls-backend-cloud-resources.labels" . | nindent 4 }}
spec:
  resourceID: {{ .Values.database.user.name | quote }}
  instanceRef:
    name: {{ .Values.database.instance.name }}
  password:
    valueFrom:
      secretKeyRef:
        name: {{ .Values.database.user.passwordSecret.name }}
        key: secret-data
{{- else }}
{{- fail "gcp.project is required" }}
{{- end }}