{{- if .Values.gcp.project }}
---
# Secret Manager Secret for Database Password
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: {{ .Values.database.user.passwordSecret.name }}
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "cls-backend-cloud-resources.labels" . | nindent 4 }}
spec:
  locations:
    - {{ .Values.gcp.region }}
  replication:
    automatic: true

---
# Secret Manager Secret Version with Password
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: {{ .Values.database.user.passwordSecret.name }}-version
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "cls-backend-cloud-resources.labels" . | nindent 4 }}
spec:
  secretRef:
    name: {{ .Values.database.user.passwordSecret.name }}
  secretData:
    {{- if .Values.database.user.passwordSecret.generatePassword }}
    # Generate a random 32-character password
    value: {{ randAlphaNum 32 | b64enc }}
    {{- else }}
    {{- if .Values.database.user.passwordSecret.password }}
    value: {{ .Values.database.user.passwordSecret.password | b64enc }}
    {{- else }}
    {{- fail "database.user.passwordSecret.password is required when generatePassword is false" }}
    {{- end }}
    {{- end }}
{{- else }}
{{- fail "gcp.project is required" }}
{{- end }}