apiVersion: v2
name: cls-backend-application
description: CLS Backend Kubernetes application deployment
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://github.com/apahim/cls-backend
maintainers:
  - name: CLS Backend Team
keywords:
  - cls
  - cluster-lifecycle
  - kubernetes
  - backend
dependencies: []
annotations:
  category: Application