apiVersion: v1
kind: Service
metadata:
  name: cls-backend-lb
  namespace: cls-system
  labels:
    app.kubernetes.io/name: cls-backend
    app.kubernetes.io/component: loadbalancer
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: cls-backend
    app.kubernetes.io/component: api-server