# Alternative secret configuration that references the PostgreSQL secret
# This approach ensures the DATABASE_URL is always in sync with PostgreSQL credentials
apiVersion: v1
kind: Secret
metadata:
  name: cls-backend-secrets
  namespace: cls-system
  labels:
    app.kubernetes.io/name: cls-backend
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  # Google Cloud Project ID
  GOOGLE_CLOUD_PROJECT: "apahim-dev-1"

  # Database URL will be injected from postgres-secret
  # This will be done via the deployment's environment variables
---
# Service to make the DATABASE_URL available to cls-backend
# The cls-backend deployment will get DATABASE_URL directly from postgres-secret
# See deployment.yaml for the environment variable configuration